support 4.2 quay.io/openshift/origin-cli oc version output
Signed-off-by: Michal Minář <miminar@redhat.com>

diff --git a/sdh-observer.yaml b/sdh-observer.yaml
--- a/sdh-observer.yaml
+++ b/sdh-observer.yaml
@@ -247,8 +247,8 @@ objects:
             fi
             # support both 3.x and 4.x output formats
             version="$(oc version --short 2>/dev/null || oc version)"
-            serverVersion="$(sed -n 's/^\([sS]erver.*:\|[oO]pen[sS]hift\) v\([0-9]\+\.[0-9]\+\).*/\2/p' \
-                              <<<"$version" | head -n 1)"
+            serverVersion="$(sed -n 's/^\(\([sS]erver\|[kK]ubernetes\).*:\|[oO]pen[sS]hift\) v\?\([0-9]\+\.[0-9]\+\).*/\3/p' \
+                              <<<"$version" | head -n 1)"; echo "serverVersion: $serverVersion"
             clientVersion="$(sed -n 's/^\([cC]lient.*:\|oc\) v\([0-9]\+\.[0-9]\+\).*/\2/p' \
                               <<<"$version" | head -n 1)"
             # translate k8s 1.13 to ocp 4.1
@@ -257,6 +257,8 @@ objects:
             fi
             if [[ -z "${clientVersion:-}" ]]; then
               printf 'WARNING: Failed to determine oc client version!\n' >&2
+            elif [[ -z "${serverVersion}" ]]; then 
+              printf 'WARNING: Failed to determine k8s server version!\n' >&2
             elif [[ "${serverVersion}" != "${clientVersion}" ]]; then
               printf 'WARNING: Client version != Server version (%s != %s).\n' "$clientVersion" "$serverVersion" >&2
               printf '         Please reinstantiate this template with the correct BASE_IMAGE_TAG parameter (e.g. v%s)."\n' >&2 \
