fixed patching of fluentd daemonset
support for SDH 2.4

Signed-off-by: Michal Minář <miminar@redhat.com>

diff --git a/sdh-observer.yaml b/sdh-observer.yaml
--- a/sdh-observer.yaml
+++ b/sdh-observer.yaml
@@ -236,7 +236,12 @@ objects:
             function get_registry() {
               if [[ -z "${registry:-}" ]]; then
                 registry="$(oc get secret -o go-template='{{index .data "installer-config.yaml"}}' installer-config | \
-                   base64 -d | sed -n 's/^\s*VFLOW_REGISTRY:\s*\(.\+\)/\1/p')"
+                   base64 -d | sed -n 's/^\s*\(DOCKER\|VFLOW\)_REGISTRY:\s*\(...\+\)/\2/p' | \
+                    tr -d '"'"'" | grep -v '^[[:space:]]*$' | tail -n 1)"
+              fi
+              if [[ -z "${registry:-}" ]]; then
+                printf "Failed to determine the registry!\n" >&2
+                return 1
               fi
               printf '%s\n' "$registry"
             }
@@ -359,10 +364,11 @@ objects:
                   '{{end}}'
                 '{{else if eq .kind "DaemonSet"}}'
                   '{{if eq .metadata.name "diagnostics-fluentd"}}'
+                    # print (string kind):(int containerIndex):(string containerName):(bool unprivileged)
                     '{{.kind}}'
                     '{{range $i, $c := $d.spec.template.spec.containers}}'
                       '{{if eq $c.name "diagnostics-fluentd"}}'
-                        $':{{$i}}:{{not $c.securityContext.privileged}}\n'
+                       $':{{$i}}:{{$c.name}}:{{not $c.securityContext.privileged}}\n'
                       '{{end}}'
                     '{{end}}'
                    $'\n'
@@ -494,16 +500,16 @@ objects:
                   ;;
 
                 daemonset)
-                  IFS=: read -r index unprivileged <<<"${rest:-}"
+                  IFS=: read -r index cname unprivileged <<<"${rest:-}"
                   name="diagnostics-fluentd"
                   if [[ "$unprivileged" == "true" ]]; then
                     printf 'Patching container #%d in daemonset/%s to make its pods privileged ...\n' \
                         "$index" "$name" >&2
-                    runOrLog oc patch "daemonset/$name" --type json -p '[{
-                      "op": "add",
-                      "path": "/spec/template/spec/containers/'"$index"'/securityContext/privileged",
-                      "value": true
-                    }]'
+                    runOrLog oc patch "daemonset/$name" -p '{"spec": {"template": {"spec": {
+                        "containers": [{
+                            "name": "'"$cname"'",
+                            "securityContext": {"privileged": true}
+                        }]}}}}'
                   else
                     printf 'Container #%d in daemonset/%s already patched, skipping ...\n' "$index" "$name" >&2
                   fi
